apiVersion: v1
kind: Pod
metadata:
  name: color-changer
  labels:
    app: color-changer
spec:
  containers:
  - name: color-changer
    image: chaozheng/colorchanger:get
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: color-changer
spec:
  type: NodePort
  selector:
    app: color-changer
  ports:
    - port: 5000
      targetPort: 5000
