# permissions for end users to view deviceservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceservice-viewer-role
rules:
- apiGroups:
  - device.openyurt.io
  resources:
  - deviceservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - deviceservices/status
  verbs:
  - get
