# permissions for end users to edit deviceservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceservice-editor-role
rules:
- apiGroups:
  - device.openyurt.io
  resources:
  - deviceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - deviceservices/status
  verbs:
  - get
