# permissions for end users to edit valuedescriptors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valuedescriptor-editor-role
rules:
- apiGroups:
  - device.openyurt.io
  resources:
  - valuedescriptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - valuedescriptors/status
  verbs:
  - get
