# permissions for end users to view valuedescriptors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: valuedescriptor-viewer-role
rules:
- apiGroups:
  - device.openyurt.io
  resources:
  - valuedescriptors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - device.openyurt.io
  resources:
  - valuedescriptors/status
  verbs:
  - get
