apiVersion: device.openyurt.io/v1alpha1
kind: DeviceProfile
metadata:
  name: sensor-cluster
spec:
  description: Sensor cluster providing metrics for temperature and humidity
  manufacturer: Raspberry Pi Foundation
  model: Raspberry Pi 3b+
  labels:
  - rpi
  deviceResources:
  - name: temperature 
    description: Sensor cluster temperature values
    properties:
      value:
        type: "Int64"
        readWrite: "RW"
        minimum: "-50"
        maximum: "100"
        size: "4"
        defaultValue: "9"
  - name: humidity 
    description: Sensor cluster humidity values
    properties:
      value:
        type: "Int64"
        readWrite: "RW"
        minimum: "0"
        maximum: "100"
        size: "4"
        defaultValue: "9"
